dataset:
  train:
    name: vkitti_depth
    disp_name: vkitti_depth_train
    dir: data/vkitti
    filenames: data_split/vkitti_depth/vkitti_train.txt
    kitti_bm_crop: true
    valid_mask_crop: null